import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "@/components/header/header";
import { CartContext } from "@/context/cartContext";
import { CartProps } from "@/utils/types";
import { useState } from "react";
import { getMyCart } from "@/services/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wicromania",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "bg-gray-100"}>
        <Toaster position="bottom-center" reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}
